### ISSUE TITLE
Not working after Feedly update

### ISSUE THREAD

**Issue by sholstein** [aaronsaray/feedlybackgroundtab#10] opened 2016-08-15 20:20 UTC
Feedly updated code around August 14 and the Chrome extension stopped working.

**Comment by aaronsaray** [comment] 2016-08-15 20:21
Thanks - but can you give more detail?  Does the screen look different?  What specific view are you using for your stories?  (I only ask these questions because I use the plugin every day and it's still working fine for me... so I'm probably not using it the same way you are).

**Comment by sholstein** [comment] 2016-08-15 20:40
Hi Aaron. Thank you for the quick reply.

Screen looks the same as when it last worked (maybe Thursday night). I'm
using Feedly on two Macbooks and the extension doesn't work on either.

I'm using default view (titles only). Since you asked I just tried Magazine
and it still didn't work.

I emailed Feedly yesterday and they said: "We cleaned up the HTML markup of
the feedly UI a lot. It could be that this cleanup might have broken that
extension. Hard to know without knowing how their extension is implemented."

I'm trying to think what else could mess with the extension.

Steve

**Comment by aaronsaray** [comment] 2016-08-15 20:44
Ok cool - I don't know how to explain this next part so bear with me... 

On the magazine layout, does it say "All" or is it broken up into multiple items?  Reason I ask is the other night I had mine broken up for one load - the plugin stopped working - and I thought I was just too tired to use the computer - went to bed.  When I woke up it was still fine... sooooo is it 'all' or are you looking at specific feeds? And then I think I saw something like "Popular" vs "All" on there too - but I can't get that to pop back up for me.  So do you see popular on yours too?

Thanks for taking the time to describe.  Might take me a few days to update this - but should be by the end of the week max.

**Comment by sholstein** [comment] 2016-08-15 20:52
On Magazine layout (which I normally don't use), "All" still looks like
default.

When I click on one of my categories Magazine layout appears.

Either way -- whether I'm in All or in one of my feed categories -- the
extension still doesn't work in Magazine view.

Thanks again!

**Comment by bval** [comment] 2016-08-15 21:21
I can confirm that this is happening in the list view as well following the latest Feedly update. The plugin outputs `Could not find any selectors from: .selectedEntry a.title,a.websiteCallForAction` in the JS console. Looking at the source it appears that the markup has changed to `.selected a.visitWebsiteButton`. I'll submit a quick PR to address this.

**Comment by jkirklan** [comment] 2016-08-16 17:06
I am having the same issue.   I see the same error in the js console.  It appears to becoming from keypress.js line 61.

**Comment by rob9283** [comment] 2016-08-17 22:39
Suggestion:  setup a PayPal donation account (or make a list a few of your favorite charities) so those of us who depend on this plugin can send $20.

**Comment by sholstein** [comment] 2016-08-17 22:47
​You'd see my donation come in very quickly.  :)​

**Comment by aaronsaray** [comment] 2016-08-19 01:13
Ok - sorry for the delay. I'll be accepting the pull request and packaging up a new feedly plugin tomorrow.
Just wanted everyone to know I haven't gone radio silent - its coming very soon! :)

**Comment by aaronsaray** [comment] 2016-08-19 18:07
Hey all - I've released a fix - thanks to @bval for his suggested pull request.

Here's the tricky part - it was always working for me - it was only broken for everyone else apparently.  Don't ask me how!  At any rate, I came up with a fix that used @bval's solution but it also works for me.  It has been pushed out to the google store.  **Please** someone comment on this ticket when you get the update to validate it's working for you.

PS: Again, thanks so much for the offers of support via paypal/donations.  Instead, I've created a kiva.org group - check out the updated readme of this project to find out more.  The short version - this software is free and I never want money - but I'd appreciate you doing good by giving loans and joining my team on that website.  Super cool - you help out people in need with loans - and you get your money back - the cycle continues!

**Comment by sholstein** [comment] 2016-08-19 19:03
Works for me! Joined your Kiva team... what's next? Do I add funds?

**Comment by aaronsaray** [comment] 2016-08-19 20:12
@sholstein yup - basically you find a loan (click the lend button) - and find a story that connects with you. Once you find someone who you feel like supporting, you click 'lend' - and then you'll 'checkout' almost like a purchase.  Again - thanks for following through and joining kiva - but if you don't find a loan that you feel compelled to make, please don't make one.  Wait until next week! There are always new ones coming and going.

I have the updated version of the plugin and it's looking well to me too.  I'm going to close this ticket.  Thanks to all that helped.

**Closed by aaronsaray** 2016-08-19 20:12 UTC
